locale: en-US
title: "Nitin Kumar Singh"
description: "My Learning and Adventures in Computer Science and Life"
baseurl: ""
url: "https://nitinitleen1.github.io"
date_format: "%Y-%m-%d"

google_analytics: "UA-155354311-1"

twitter:
  username: "nitinkumarsin10"

# Liquid
liquid:
  error_mode: strict

# Build settings
exclude:
  - docs
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md

permalink: /:title/
markdown: kramdown
feed:
  path: atom.xml

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Front Matter Defaults
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post

# Site Author
author:
  name: Nitin
  picture: /assets/nks1.png
  twitter: https://twitter.com/nitinkumarsin10
  links:
    - title: LinkedIn
      url: https://linkedin.com/in/nitinnks

social:
  name: Nitin
  links:
    - https://twitter.com/nitinkumarsin10
    - https://www.linkedin.com/in/nitinnks/

copyright: "©2019 All Rights Reserved."
